name: tp0
services:
  server:
    container_name: server
    image: server:latest
    volumes:
      - ./server/config.ini:/config.ini:ro
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
      
  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml:ro
      - ./.data/agency-1.csv:/.data/agency.csv:ro
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Santiago
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
  client2:
    container_name: client2
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml:ro
      - ./.data/agency-2.csv:/.data/agency.csv:ro
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE=Santiago
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
  client3:
    container_name: client3
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml:ro
      - ./.data/agency-3.csv:/.data/agency.csv:ro
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NOMBRE=Santiago
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
  client4:
    container_name: client4
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml:ro
      - ./.data/agency-4.csv:/.data/agency.csv:ro
    entrypoint: /client
    environment:
      - CLI_ID=4
      - NOMBRE=Santiago
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
  client5:
    container_name: client5
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml:ro
      - ./.data/agency-5.csv:/.data/agency.csv:ro
    entrypoint: /client
    environment:
      - CLI_ID=5
      - NOMBRE=Santiago
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
